# Generated by Django 4.1.2 on 2022-10-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.URLField(max_length=500)),
                ('release_date', models.DateTimeField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
